model:
  name: CancerResNet18
  output_dim: 2
  n_blocks: [2, 2, 2, 2]
  n_channels: [64, 128, 256, 512]

optimizer:
  name: Adam
  parameters:
    lr: 0.001
    weight_decay: 0.0005

#scheduler:
#  num: 1
#  scheduler0:
#    name: ExponentialLR
#    parameters:
#      gamma: 0.5

dataset:
  name: cancer
  data_dir: ./data
  batch_size: 64
  split:
    train: 0.9
    valid: 0.1
    test: 1.0

train:
  epochs: 50
  device: cuda:0
  save_path: ./checkpoints/
  log_path: ./logs/
  seed: 42
  save_every: 2

test:
  device: cuda:0
  checkpoint: ./checkpoints/
  log_path: ./logs/
  seed: 42
